# automatically generated by the FlatBuffers compiler, do not modify

# namespace: schema

# The possible types of things that can exist.
class BodyType(object):
    HEADQUARTERS = 0
    CARRIER = 1
    LAUNCHER = 2
    AMPLIFIER = 3
    DESTABILIZER = 4
    BOOSTER = 5
