# automatically generated by the FlatBuffers compiler, do not modify

# namespace: schema

# Events
# An Event is a single step that needs to be processed.
# A saved game simply consists of a long list of Events.
# Events can be divided by either being sent separately (e.g. as separate
# websocket messages), or by being wrapped with a GameWrapper.
# A game consists of a series of matches; a match consists of a series of
# rounds, and is played on a single map. Each round is a single simulation
# step.
class Event(object):
    NONE = 0
    # There should only be one GameHeader, at the start of the stream.
    GameHeader = 1
    # There should be one MatchHeader at the start of each match.
    MatchHeader = 2
    # A single simulation step. A round may be skipped if
    # nothing happens during its time.
    Round = 3
    # There should be one MatchFooter at the end of each simulation step.
    MatchFooter = 4
    # There should only be one GameFooter, at the end of the stream.
    GameFooter = 5
