# automatically generated by the FlatBuffers compiler, do not modify

# namespace: schema

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

# The first event sent in the game. Contains all metadata about the game.
class GameHeader(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = GameHeader()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsGameHeader(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # GameHeader
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # The version of the spec this game complies with.
    # GameHeader
    def SpecVersion(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # The teams participating in the game.
    # GameHeader
    def Teams(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            from battlecode.schema.TeamData import TeamData
            obj = TeamData()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # GameHeader
    def TeamsLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # GameHeader
    def TeamsIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        return o == 0

    # Information about all body types in the game.
    # GameHeader
    def BodyTypeMetadata(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            from battlecode.schema.BodyTypeMetadata import BodyTypeMetadata
            obj = BodyTypeMetadata()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # GameHeader
    def BodyTypeMetadataLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # GameHeader
    def BodyTypeMetadataIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        return o == 0

    # GameHeader
    def Constants(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            from battlecode.schema.Constants import Constants
            obj = Constants()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

def GameHeaderStart(builder): builder.StartObject(4)
def Start(builder):
    return GameHeaderStart(builder)
def GameHeaderAddSpecVersion(builder, specVersion): builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(specVersion), 0)
def AddSpecVersion(builder, specVersion):
    return GameHeaderAddSpecVersion(builder, specVersion)
def GameHeaderAddTeams(builder, teams): builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(teams), 0)
def AddTeams(builder, teams):
    return GameHeaderAddTeams(builder, teams)
def GameHeaderStartTeamsVector(builder, numElems): return builder.StartVector(4, numElems, 4)
def StartTeamsVector(builder, numElems):
    return GameHeaderStartTeamsVector(builder, numElems)
def GameHeaderAddBodyTypeMetadata(builder, bodyTypeMetadata): builder.PrependUOffsetTRelativeSlot(2, flatbuffers.number_types.UOffsetTFlags.py_type(bodyTypeMetadata), 0)
def AddBodyTypeMetadata(builder, bodyTypeMetadata):
    return GameHeaderAddBodyTypeMetadata(builder, bodyTypeMetadata)
def GameHeaderStartBodyTypeMetadataVector(builder, numElems): return builder.StartVector(4, numElems, 4)
def StartBodyTypeMetadataVector(builder, numElems):
    return GameHeaderStartBodyTypeMetadataVector(builder, numElems)
def GameHeaderAddConstants(builder, constants): builder.PrependUOffsetTRelativeSlot(3, flatbuffers.number_types.UOffsetTFlags.py_type(constants), 0)
def AddConstants(builder, constants):
    return GameHeaderAddConstants(builder, constants)
def GameHeaderEnd(builder): return builder.EndObject()
def End(builder):
    return GameHeaderEnd(builder)